### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by Neustradamus** [tilkinsc/COTP#27]
Dear @tilkinsc,

Thanks for your work!

Can you add you in public here?
- https://github.com/orgs/OTPLibraries/people

Can you remove all forks in:
- https://github.com/OTPLibraries

Can you transfer your main OTP repositories into the OTPLibraries organization?

Thanks in advance.

**Comment by tilkinsc** [comment]
I instead just deleted OTPLibraries (its a pain to manage). They will remain under my namespace.

**Comment by Neustradamus** [comment]
@tilkinsc: Thanks for your quick answer!

But it is easy, you can create again the organization, and do the transfer into.
The redirection will be here no lost from old place to new...
And it is easy to manage.

**Comment by tilkinsc** [comment]
Ok
