### ISSUE TITLE
Doesn't use cryptographically safe random for time

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/COTP#4]

**Comment by ppsilv** [comment]
Hi , may you provide more especific description for this issue.

**Comment by tilkinsc** [comment]
Basically you can, with knowledge of when the key was generated, regenerate the random base 32 code and get access to creating TOTP compliant with 30 seconds and 6 digits. Not much of a security flaw if no ghosting happens. Using the cryptographically secure random that OpenSSL provides for a number rather than relying on system time will allow you to avoid problems. PyOTP was suggest a poll request for this to be changed, however, my library doesn't have the portability that a script language does, for example, so I have to rely on OpenSSL as a dependency for correctness. However, the work around for that would be creating a function pointer that relies on you to do such a generation, much like the hmac generation functions found in the test/example files.

**Comment by tilkinsc** [comment]
User can now specify their own time as of e8094a6
