### ISSUE TITLE
Code Generator not 100% compatible

### ISSUE THREAD

**Issue by marbetschar** [tilkinsc/COTP#5]
Seems like there is an issue in the code generation algorithm in this library, which leads to incompatibilities when compared to other implementations (read "produces different codes than other libraries").

To make things worse this does not always happen, only about 1/10 of the time. Below is what I got when I compared the codes generated by this library with https://github.com/samdjstevens/java-totp (please note: it does not matter whether the secret is generated in COTP or in Java TOTP - the behaviour is the same in both cases).

FWIW: I used the `otp-cli` tool in my tests which is in https://github.com/OTPLibraries/COTP/pull/5

Here are the test results:

```bash
Starting 30 test(s) with dynamic secret(s)...
Fre Mär 19 10:43:13 CET 2021 Success: Code 346354 matches (secret = 'APGLZGHY3LIWP76N')
Fre Mär 19 10:43:17 CET 2021 Success: Code 493943 matches (secret = 'DMNZQPSQXANP3MP3')
Fre Mär 19 10:43:21 CET 2021 Success: Code 665198 matches (secret = '62JRHI76LTYAQTIK')
Fre Mär 19 10:43:25 CET 2021 Success: Code 621885 matches (secret = '7T7RLCNRVKFP34FA')
Fre Mär 19 10:43:29 CET 2021 Error: Code 082255 does not match with java version (java code = '528876', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:34 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:38 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:42 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:46 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:50 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:54 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:43:58 CET 2021 Error: Code 388616 does not match with java version (java code = '319556', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:44:02 CET 2021 Error: Code 420660 does not match with java version (java code = '029143', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:44:06 CET 2021 Error: Code 420660 does not match with java version (java code = '029143', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:44:10 CET 2021 Error: Code 420660 does not match with java version (java code = '029143', secret = 'TWH3C5SBQV2SW6HI')
Fre Mär 19 10:44:14 CET 2021 Too many retries for secret 'TWH3C5SBQV2SW6HI'... Giving up.
Fre Mär 19 10:44:14 CET 2021 Success: Code 409665 matches (secret = 'RSLXPFQLCURTL4EP')
Fre Mär 19 10:44:19 CET 2021 Success: Code 968733 matches (secret = 'DVUODLDV2IHU2JFI')
Fre Mär 19 10:44:23 CET 2021 Success: Code 947597 matches (secret = '4PRG3YINFDS335HU')
Fre Mär 19 10:44:27 CET 2021 Success: Code 493943 matches (secret = 'NARZDZDMY4QIUPXE')
Fre Mär 19 10:44:31 CET 2021 Success: Code 099346 matches (secret = '3YSUYMT53DVCOCFG')
Fre Mär 19 10:44:35 CET 2021 Success: Code 194446 matches (secret = 'B7XMT5M3XNIDTCCZ')
Fre Mär 19 10:44:39 CET 2021 Success: Code 167852 matches (secret = 'C5TBDBCUDLUQUYOK')
Fre Mär 19 10:44:43 CET 2021 Success: Code 861182 matches (secret = 'GDXSG2KHU7OGFRXH')
Fre Mär 19 10:44:47 CET 2021 Success: Code 280202 matches (secret = 'TQ76H5WTALISGMD6')
Fre Mär 19 10:44:51 CET 2021 Success: Code 659381 matches (secret = 'AHLMCMKW4EOGSOVR')
Fre Mär 19 10:44:55 CET 2021 Success: Code 275554 matches (secret = 'YCSQQBSJS2X2HCIK')
Fre Mär 19 10:45:00 CET 2021 Success: Code 018522 matches (secret = '7WES6H6473WA4RSZ')
Fre Mär 19 10:45:04 CET 2021 Success: Code 914032 matches (secret = 'GXMJQPHR5YK4QOPR')
Fre Mär 19 10:45:08 CET 2021 Success: Code 228612 matches (secret = 'HMZMPIUKFVXUF6UT')
Fre Mär 19 10:45:12 CET 2021 Success: Code 012979 matches (secret = '5ZMRZRXIBFXWEN7J')
```

**Comment by tilkinsc** [comment]
This library isn't full conformant with the RFC. Not entirely sure why it wouldn't be working. Also not sure if its a problem with their repo or mine. Any subtle differences between will cause my library to fail as the library doesn't have any input or internal validation of parameters. Further, the front end you used isn't designed to do more than just test the library in-code. It isn't a tool. Or at least, I don't remember it being a tool.

**Comment by marbetschar** [comment]
> This library isn't full conformant with the RFC.

Alright, good to know. Any chance you are aware which specifics are not conformant and/or missing?

> Further, the front end you used isn't designed to do more than just test the library in-code. It isn't a tool. Or at least, I don't remember it being a tool.

I don't think I understand what you mean with this. Which "front end" or "tool" do you mean? Can you elaborate?

**Comment by tilkinsc** [comment]
The base32 generation is fake and it doesn't accept the full range of bits. So some base32 secrets won't work that's outside the range.

https://github.com/tilkinsc/COTP/blob/master/test/main.cpp
This is a test tool, not a front end. This is what I meant.

**Comment by tilkinsc** [comment]
My library should now be fully conformant.

Please test and decide to close.

**Comment by Jbuckmsi** [comment]
I can confirm this is still an issue.

Try this as your BASE32_SECRET  "3E56263A4A655ED7"

tdata.now() gives a different result then other libraries and authenticators.

**Comment by tilkinsc** [comment]
I will give it a go. Did you use the example or did you use your own code?

**Comment by Jbuckmsi** [comment]
Used the example.  Just switched the BASE32_SECRET

**Comment by tilkinsc** [comment]
In said libraries did you use the base32_secret as ascii as the buffer, or did you unbase32 before using it?

**Comment by tilkinsc** [comment]
I added some commits after the fact that should have cured this. Awaiting testing to close.

**Comment by tilkinsc** [comment]
I tested and yes its my library thats generating a wrong code for `3E56263A4A655ED7` I am really gaslit because the code looks perfect and is well tested.

**Comment by tilkinsc** [comment]
af78c82 should fix this issue closing since no response

**Comment by edwRoland** [comment]
Still an issue for me.

I'm using OpenSSL 1.1.1q with this code:

`#include <iostream>
#include <cstdlib>
#include <iostream>
#include <cstring>
#include <chrono>
#include <thread>

#include "cotp.hpp"

#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/sha.h>

using namespace std;

static const int32_t SHA1_BYTES = 160 / 8;	// 20

int hmac_algo_sha1(const char* byte_secret, const char* byte_string, char* out)
{
  // Output len
  unsigned int len = SHA1_BYTES;

  unsigned char* result = HMAC(
    EVP_sha1(),							// algorithm
    (unsigned char*)byte_secret, 10,	// key
    (unsigned char*)byte_string, 8,		// data
    (unsigned char*)out,				// output
    &len								// output length
  );

  // Return the HMAC success
  return result == 0 ? 0 : len;
}

uint64_t get_current_time()
{
  using namespace std::chrono;

  auto now = system_clock::now();
  auto dur = now.time_since_epoch();

  return duration_cast<chrono::seconds>(dur).count();
}

int main()
{
  const int INTERVAL = 5;
  const int DIGITS = 6;

  string secret = "3E56263A4A655ED7";

  class TOTP tdata(secret.c_str(), hmac_algo_sha1, get_current_time, DIGITS, INTERVAL);

  while (1)
  {
    char tcode[DIGITS + 1];
    memset(tcode, 0, DIGITS + 1);

    tdata.now(tcode);

    system("cls");

    cout << "CODE: " << tcode << endl;

    std::this_thread::sleep_for(std::chrono::seconds(1));
  }
}`

and it produces different codes like from google authenticator or from this online TOTP tool
https://totp.danhersam.com/
With are generating the same code btw

**Comment by tilkinsc** [comment]
Google authenticator might not support an INTERVAL of 5.
